// apps/solid/src/App.tsx
import { streamAgent } from "./lib/agentStream";
import { createSignal, For, Show } from "solid-js";

type Bubble = {
  role: "assistant" | "user";
  content: string;
};

export function App() {
  let prompt!: HTMLInputElement;
  const [bubbles, setBubbles] = createSignal<Bubble[]>([]);
  const [activeBubble, setActiveBubble] = createSignal<Bubble | null>(null);
  const [pending, setPending] = createSignal<boolean>(false);

  const submitPrompt = async (event: SubmitEvent) => {
    event.preventDefault();
    if (!prompt || pending()) return;

    const text = prompt.value.trim();
    if (!text) return;

    setBubbles(prev => [...prev, { role: "user", content: text }]);
    setActiveBubble({ role: "assistant", content: "" });
    setPending(true);
    prompt.value = "";

    try {
      const abortController = new AbortController();
      await streamAgent({
        userId: "a311151e-d40a-4369-94ec-c86fcff67d7c",
        sessionId: "8c4529c2-1d70-4abe-b255-fba16baa15fb",
        message: text,
        onEvent: (event) => {
          if (event.type === "text-delta") {

            setActiveBubble(prev => (
              prev && { ...prev, content: prev.content + event.delta }
            ));
          }
          if (event.type === "done") {
            if (activeBubble()) {
              setBubbles(prev => [...prev, activeBubble()!]);
            }
            setActiveBubble(null);
            setPending(false);
          }
          if (event.type === "error") {
            setBubbles(prev => [...prev, { role: "assistant", content: `Error: ${event.message}` }]);
            setActiveBubble(null);
            setPending(false);
          }
        },
        signal: abortController.signal,
      });
    } catch (error) {
      const message = error instanceof Error ? error.message : "Unknown error";
      setBubbles(prev => [...prev, { role: "assistant", content: `Error: ${message}` }]);
      setActiveBubble(null);
      setPending(false);
    } finally {
      setPending(false);
    }
  };

  return (
    <div class="deck variant-e">
      <div class="ambient" aria-hidden="true" />

      <header class="topbar">
        <div class="brand">
          <span class="status-dot" />
          Malkier Command Deck
        </div>
        <div class="meta">static solid shell | chat-first agent</div>
      </header>

      <main class="layout">
        <section class="panel chat-panel">
          <div class="panel-title">Agent Session</div>
          <div class="chat-log">
            <For each={bubbles()}>
              {(bubble) => (
                <article class="bubble" classList={{ user: bubble.role === "user", assistant: bubble.role === "assistant" }}>
                  <div class="bubble-role">{bubble.role === "assistant" ? "agent" : "you"}</div>
                  <p>{bubble.content}</p>
                </article>
              )}
            </For>
            <Show when={activeBubble() !== null}>
              <article class="bubble assistant">
                <div class="bubble-role">agent</div>
                <p>{activeBubble()?.content}</p>
              </article>
            </Show>
          </div>

          <form class="composer" onSubmit={submitPrompt}>
            <input ref={prompt} placeholder="Ask to explain codebase or fix a bug" disabled={pending()} />
            <button type="submit" disabled={pending()}>{pending() ? "running" : "dispatch"}</button>
          </form>
        </section>

        <aside class="stack">
          <section class="panel">
            <div class="panel-title">Task Queue 50%</div>
            <ul class="tasks">
              <li class="task completed">
                <span class="task-chip">completed</span>
                <span>Inspect failing area</span>
              </li>
              <li class="task in_progress">
                <span class="task-chip">in progress</span>
                <span>Propose fix plan</span>
              </li>
              <li class="task pending">
                <span class="task-chip">pending</span>
                <span>Apply code edits</span>
              </li>
              <li class="task pending">
                <span class="task-chip">pending</span>
                <span>Run tests</span>
              </li>
            </ul>
          </section>

          <section class="panel">
            <div class="panel-title">Terminal Output</div>
            <div class="terminal">
              <p class="line cmd">$ rg "health" packages/payments/src</p>
              <p class="line out">health.ts
                health.test.ts
                health-client.ts</p>
              <p class="line ok">Patched 2 files successfully</p>
            </div>
          </section>

          <section class="panel">
            <div class="panel-title">Diff Preview</div>
            <div class="diff-grid">
              <article class="diff-file">
                <div class="diff-head">
                  <span>packages/payments/src/health.ts</span>
                  <span>+14 -6</span>
                </div>
                <pre>
                  <code class="ctx">@@ export async function waitForHealthyService(...) @@</code>
                  <code class="remove">-const timeoutMs = 500;</code>
                  <code class="add">+const timeoutMs = opts.timeoutMs ?? 1500;</code>
                  <code class="remove">-if (status === 'ready') return true;</code>
                  <code class="add">+if (status === 'ready' || status === 'warm') return true;</code>
                  <code class="add">+await jitteredBackoff(attempt);</code>
                </pre>
              </article>

              <article class="diff-file">
                <div class="diff-head">
                  <span>packages/payments/src/health.test.ts</span>
                  <span>+11 -1</span>
                </div>
                <pre>
                  <code class="ctx">@@ test('returns true during warm transition') @@</code>
                  <code class="add">+it('accepts warm state before ready', async () =&gt; &#123;</code>
                  <code class="add">
                    + const result = await waitForHealthyService(mockClient, &#123; timeoutMs: 1200 &#125;);
                  </code>
                  <code class="add">+ expect(result).toBe(true);</code>
                  <code class="add">+&#125;);</code>
                </pre>
              </article>
            </div>
          </section>
        </aside>
      </main>
    </div>
  );
}

export default App;

// apps/demo/src/App.tsx
import { useMemo, useRef, useState } from "react";
import type { FormEvent } from "react";
import "./styles.css";

type Role = "user" | "assistant";
type TaskState = "pending" | "in_progress" | "completed";

type ChatMessage = {
  id: string;
  role: Role;
  content: string;
};

type TodoItem = {
  id: string;
  label: string;
  state: TaskState;
};

type TerminalLine = {
  id: string;
  kind: "cmd" | "out" | "ok";
  text: string;
};

type DiffFile = {
  path: string;
  summary: string;
  patch: string[];
};

const initialMessage: ChatMessage = {
  id: "boot",
  role: "assistant",
  content:
    "Command deck online. Ask me to explain code or run a bug-fix flow. Try: fix flaky health-check test in payments module.",
};

const initialTasks: TodoItem[] = [
  { id: "inspect", label: "Inspect failing area", state: "pending" },
  { id: "plan", label: "Propose fix plan", state: "pending" },
  { id: "patch", label: "Apply code edits", state: "pending" },
  { id: "verify", label: "Run tests", state: "pending" },
];

const demoDiff: DiffFile[] = [
  {
    path: "packages/payments/src/health.ts",
    summary: "+14 -6",
    patch: [
      "@@ export async function waitForHealthyService(...) @@",
      "-const timeoutMs = 500;",
      "+const timeoutMs = opts.timeoutMs ?? 1500;",
      "-if (status === 'ready') return true;",
      "+if (status === 'ready' || status === 'warm') return true;",
      "+await jitteredBackoff(attempt);",
    ],
  },
  {
    path: "packages/payments/src/health.test.ts",
    summary: "+11 -1",
    patch: [
      "@@ test('returns true during warm transition') @@",
      "+it('accepts warm state before ready', async () => {",
      "+  const result = await waitForHealthyService(mockClient, { timeoutMs: 1200 });",
      "+  expect(result).toBe(true);",
      "+});",
    ],
  },
];

const wait = (ms: number) => new Promise<void>(resolve => setTimeout(resolve, ms));

export function App() {
  const [prompt, setPrompt] = useState("");
  const [busy, setBusy] = useState(false);
  const [messages, setMessages] = useState<ChatMessage[]>([initialMessage]);
  const [tasks, setTasks] = useState<TodoItem[]>(initialTasks);
  const [terminal, setTerminal] = useState<TerminalLine[]>([]);
  const [diff, setDiff] = useState<DiffFile[]>([]);
  const idRef = useRef(0);

  const completion = useMemo(() => {
    const done = tasks.filter(item => item.state === "completed").length;
    return Math.round((done / tasks.length) * 100);
  }, [tasks]);

  const nextId = () => {
    idRef.current += 1;
    return `${idRef.current}`;
  };

  const pushMessage = (role: Role, content: string) => {
    setMessages(prev => [...prev, { id: nextId(), role, content }]);
  };

  const pushTerminal = (kind: TerminalLine["kind"], text: string) => {
    setTerminal(prev => [...prev, { id: nextId(), kind, text }]);
  };

  const markTask = (id: string, state: TaskState) => {
    setTasks(prev => prev.map(task => (task.id === id ? { ...task, state } : task)));
  };

  const runScenario = async (userPrompt: string) => {
    setBusy(true);
    setTasks(initialTasks);
    setTerminal([]);
    setDiff([]);

    pushMessage("assistant", "Copy. I will inspect the bug, propose a plan, patch it, then run tests.");

    markTask("inspect", "in_progress");
    pushTerminal("cmd", "$ rg \"health\" packages/payments/src");
    await wait(900);
    pushTerminal("out", "health.ts\nhealth.test.ts\nhealth-client.ts");
    markTask("inspect", "completed");

    markTask("plan", "in_progress");
    await wait(700);
    pushMessage(
      "assistant",
      "Plan: widen the readiness condition to include warm state, increase timeout tolerance, then add one regression test.",
    );
    markTask("plan", "completed");

    markTask("patch", "in_progress");
    pushTerminal("cmd", "$ apply patch to health.ts and health.test.ts");
    await wait(900);
    setDiff(demoDiff);
    pushTerminal("ok", "Patched 2 files successfully");
    markTask("patch", "completed");

    markTask("verify", "in_progress");
    pushTerminal("cmd", "$ bun test packages/payments/src/health.test.ts");
    await wait(950);
    pushTerminal("out", "4 passed, 0 failed, 18 assertions");
    pushTerminal("ok", "Test command exited with code 0");
    markTask("verify", "completed");

    pushMessage(
      "assistant",
      `Done. I fixed the flaky readiness logic and added a regression test. Request: ${userPrompt}`,
    );
    setBusy(false);
  };

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const text = prompt.trim();
    if (!text || busy) return;

    setMessages(prev => [...prev, { id: nextId(), role: "user", content: text }]);
    setPrompt("");
    void runScenario(text);
  };

  return (
    <div className="deck variant-e">
      <div className="ambient" aria-hidden />

      <header className="topbar">
        <div className="brand">
          <span className="status-dot" />
          Malkier Command Deck
        </div>
        <div className="meta">mocked session | chat-first agent</div>
      </header>

      <main className="layout">
        <section className="panel chat-panel">
          <div className="panel-title">Agent Session</div>
          <div className="chat-log">
            {messages.map(item => (
              <article key={item.id} className={`bubble ${item.role}`}>
                <div className="bubble-role">{item.role === "assistant" ? "agent" : "you"}</div>
                <p>{item.content}</p>
              </article>
            ))}
          </div>

          <form className="composer" onSubmit={submit}>
            <input
              value={prompt}
              onChange={event => setPrompt(event.target.value)}
              placeholder="Ask to explain codebase or fix a bug"
              disabled={busy}
            />
            <button type="submit" disabled={busy}>
              {busy ? "running" : "dispatch"}
            </button>
          </form>
        </section>

        <aside className="stack">
          <section className="panel">
            <div className="panel-title">Task Queue {completion}%</div>
            <ul className="tasks">
              {tasks.map(task => (
                <li key={task.id} className={`task ${task.state}`}>
                  <span className="task-chip">{task.state.replace("_", " ")}</span>
                  <span>{task.label}</span>
                </li>
              ))}
            </ul>
          </section>

          <section className="panel">
            <div className="panel-title">Terminal Output</div>
            <div className="terminal">
              {terminal.length === 0 && <p className="placeholder">No commands executed yet.</p>}
              {terminal.map(line => (
                <p key={line.id} className={`line ${line.kind}`}>
                  {line.text}
                </p>
              ))}
            </div>
          </section>

          <section className="panel">
            <div className="panel-title">Diff Preview</div>
            <div className="diff-grid">
              {diff.length === 0 && <p className="placeholder">Patched files will appear here.</p>}
              {diff.map(file => (
                <article key={file.path} className="diff-file">
                  <div className="diff-head">
                    <span>{file.path}</span>
                    <span>{file.summary}</span>
                  </div>
                  <pre>
                    {file.patch.map(line => (
                      <code
                        key={`${file.path}-${line}`}
                        className={line.startsWith("+") ? "add" : line.startsWith("-") ? "remove" : "ctx"}
                      >
                        {line}
                      </code>
                    ))}
                  </pre>
                </article>
              ))}
            </div>
          </section>
        </aside>
      </main>
    </div>
  );
}
